/**
 * ◈ GARFIELD-V11-CORE ◈
 * * This architectural core is engineered for performance.
 * Designed & Developed by Tharindu Liyanage
 * * © 2026 Xnodes Laboratory. All rights reserved.
 * ---------------------------------------------------------
 */
const{commands:t}=require("../command"),{pipeline:e}=require("stream/promises"),fs=require("fs"),path=require("path"),axios=require("axios"),yts=require("yt-search"),{createDecipheriv:a}=require("crypto"),TEMP=path.join(__dirname,"../lib/store");function get_id(t){let e=t.match(/(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|v\/|embed\/|user\/[^\/\n\s]+\/)?(?:watch\?v=|v%3D|embed%2F|video%2F)?|youtu\.be\/|youtube\.com\/watch\?v=|youtube\.com\/embed\/|youtube\.com\/v\/|youtube\.com\/shorts\/|youtube\.com\/playlist\?list=)([a-zA-Z0-9_-]{11})/);return e?e[1]:null}fs.existsSync(TEMP)||fs.mkdirSync(TEMP,{recursive:!0});const decode=t=>{try{let e=Buffer.from(t,"base64"),o=e.slice(0,16),i=e.slice(16),n=Buffer.from("C5D58EF67A7584E4A29F6C35BBC4EB12","hex"),s=a("aes-128-cbc",n,o),r=Buffer.concat([s.update(i),s.final()]);return JSON.parse(r.toString())}catch(u){return null}};async function savetube(t,e,a){let o=(await axios.get("https://media.savetube.vip/api/random-cdn")).data.cdn,i=(await axios.post("https://"+o+"/v2/info",{url:t})).data,n=decode(i.data);if(!n)throw Error("Decryption failed");let s=(await axios.post("https://"+o+"/download",{downloadType:a,quality:`${e}`,key:n.key})).data;return{downloadUrl:s.data.downloadUrl,title:n.title||"Audio",duration:n.durationLabel||"00:00"}}t.push({pattern:"song",alias:["mp3"],react:"\uD83C\uDFB5",async function(t,a,o){let{from:i,q:n,reply:s}=o;if(!n)return s("⚠️ Provide a song name or YouTube link!\nExample: *.song shape of you*");let r=n.trim(),u={};try{if(get_id(r)){let l=await yts({videoId:get_id(r)});u=l}else{let d=await yts(n),c=d.videos[0];if(!c)return s("❌ No results found.");r=c.url,u=c}}catch(m){return s("❌ YouTube search failed.")}try{await t.sendMessage(i,{image:{url:u.thumbnail||u.image||"https://i.imgur.com/u3gHwXG.png"},caption:`*🎵 ${u.title||"Unknown Title"}*
*⏱️ Duration:* ${u.timestamp||u.duration?.toString()||"N/A"}
*👤 Artist:* ${u.author?.name||"Unknown Author"}

_Downloading..._`},{quoted:a})}catch(p){}let y;try{y=await savetube(r,128,"audio")}catch(h){return s("❌ Connection failed.")}let f=y.title.replace(/[/\\?%*:|"<>]/g,"-"),w=path.join(TEMP,`song_${f}_${Date.now()}.mp3`);try{let g=await axios({method:"get",url:y.downloadUrl,responseType:"stream"});if(await e(g.data,fs.createWriteStream(w)),!fs.existsSync(w)||0===fs.statSync(w).size)throw Error("Empty file payload received");await t.sendMessage(i,{audio:{url:w},mimetype:"audio/mpeg",ptt:!1},{quoted:a})}catch(b){return s(`❌ Error: ${b.message}`)}finally{fs.existsSync(w)&&fs.unlinkSync(w)}}});
